name: Post status check
description: Create status check in target repository based on result of the current workflow run.
inputs:
  github-token:
    description: A valid GitHub token that can create status check in target repository
    default: ${{ github.token }}
    required: false
  owner:
    description: Name of the repository owner
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: Name of the repository where the status should be created
    default: "datadog-api-spec"
    required: false
  pull-request:
    description: Pull-request number
    required: false
  context:
    description: Name of the status check
    required: true
  status:
    description: A valid status value for the commit
    default: "success"
    required: false
outputs:
  result:
    description: "Commit status details"
    value: ${{ steps.status.result }}
runs:
  using: "node12"
  main: "../lib/post-status-check.js"
